TITLE 'MANOVA';
DATA NYC_Felony;
INFILE 'MV.DAT';
INPUT BOUROUGH $ PERCINCT MURDER RAPE ROBBERY ASSAULT BURGLARY LARCENY MOTOR_LARCENY;
PROC GLM;
CLASS BOUROUGH;
MODEL MURDER RAPE ROBBERY ASSAULT BURGLARY LARCENY MOTOR_LARCENY = BOUROUGH;
MANOVA H=BOUROUGH/PRINTE PRINTH;
RUN;
