DATA work.FELONY;

  INFILE "/folders/myfolders/data/nyc_felony.dat";
  INPUT OBS OBS1 X1 X2 X3 X4 X5 X6 X7;

TITLE "Project STA 9705: NYC Felony";


PROC FACTOR METHOD=PRIN NFACT=2 ROTATE=VARIMAX SCREE EV PLOT = ALL;
VAR X1-X7;

RUN;

PROC FACTOR METHOD=PRIN PRIORS=SMC NFACT=2 ROTATE=VARIMAX PLOT = ALL;
VAR X1-X7;
RUN;